# Generated by Django 5.0.7 on 2024-08-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='alternative_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
